### ISSUE TITLE
Missing cc in buganizer bugs filed by CF

### ISSUE THREAD

**Issue by hzawawy** [google/clusterfuzz#1315]
For fuzz targets where cc_fuzz/config contains cc: ["abc@xyz.com"], this is expected be in the cc of bugs filed in buganizer. Currently, this is not the case, e.g  b/146452373 which should have cc owners list in aidl_parser_fuzzer (see  https://android.googlesource.com/platform/system/tools/aidl/+/refs/heads/master/Android.bp)

**Comment by oliverchang** [comment]
It looks like there were multiple problems here.

For the example you linked specifically, it appears that the build had an incorrect metadata filename format for the CCs (".owners" instead of "<target>.owners"). This appears to have been fixed in later builds, but this metadata is only added at the time of finding the bug during fuzzing (at which point it was incorrect). 

The second issue is that we were missing a hotlist config for that deployment of CF that prevented this from working as expected. I'll add it now.

**Comment by oliverchang** [comment]
This appears to be working now. See e.g. b/145713226
