### ISSUE TITLE
Issue with non-ascii environment variables

### ISSUE THREAD

**Issue by eepeep** [google/clusterfuzz#1360]
I have some non-ascii characters in my PS1, and this causes problems with some of the code in #1336 .  For example, running some integration tests, I see:

```
Traceback (most recent call last):
  File "~/clusterfuzz/src/python/tests/core/bot/fuzzers/libFuzzer/engine_test.py", line 1017, in test_qemu_logs_returned_on_error
    build_manager.setup_build()
  File "~/clusterfuzz/src/python/build_management/build_manager.py", line 1418, in setup_build
    return setup_trunk_build(bucket_paths, target_weights=target_weights)
  File "~/clusterfuzz/src/python/build_management/build_manager.py", line 1212, in setup_trunk_build
    target_weights=target_weights)
  File "~/clusterfuzz/src/python/build_management/build_manager.py", line 1256, in setup_regular_build
    if build.setup():
  File "~/clusterfuzz/src/python/build_management/build_manager.py", line 783, in setup
    fuchsia.device.initial_qemu_setup()
  File "~/clusterfuzz/src/python/platforms/fuchsia/device.py", line 99, in initial_qemu_setup
    extend_fvm(qemu_vars['fuchsia_resources_dir'], qemu_vars['drive_path'])
  File "~/clusterfuzz/src/python/platforms/fuchsia/device.py", line 228, in extend_fvm
    result = process.run_and_wait()
  File "~/clusterfuzz/src/python/system/new_process.py", line 344, in run_and_wait
    **popen_args)
  File "~/clusterfuzz/src/python/system/new_process.py", line 283, in run
    for k, v in env.items()
  File "~/clusterfuzz/src/python/system/new_process.py", line 283, in <dictcomp>
    for k, v in env.items()
  File "~/clusterfuzz/src/python/base/utils.py", line 949, in newstr_to_native_str
    return future_utils.native(str(s)).encode()
  File "~/clusterfuzz/ENV/local/lib/python2.7/site-packages/future/types/newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 6: ordinal not in range(128)
```

I was able to fix this by simply removing the conversion of environment variables in https://github.com/google/clusterfuzz/blob/25703fe2372817765e/src/python/system/new_process.py#L278-L284 , but I'm not sure this is a proper fix (I wasn't able to find the subprocess type checks mentioned in the TODO).  Happy to send a PR with this, but thought I'd ask for your input first.  Thanks!

**Comment by oliverchang** [comment]
I don't think removing the conversions is the correct fix here, as this was fixing another exception. @mbarbella-chromium maybe we can just add 'utf-8' to the str() call of: 

```python
# TODO(mbarbella): Delete this once fully migrated to Python 3.
def newstr_to_native_str(s):
  return future_utils.native(str(s, encoding='utf-8')).encode()  
```

While we're here, should .encode() be called under Python 3? As is, this funtions will not return the native "str" on Python 3 and return a bytes instead.

**Comment by mbarbella-chromium** [comment]
> I don't think removing the conversions is the correct fix here, as this was fixing another exception. @mbarbella-chromium maybe we can just add 'utf-8' to the str() call of:

That seems reasonable to me.

> While we're here, should .encode() be called under Python 3? As is, this funtions will not return the native "str" on Python 3 and return a bytes instead.

future_utils.native actually returns a unicode (since it's the native type backing newstr), so this should be safe.

**Comment by eepeep** [comment]
Thanks for the quick reply.  FWIW I'm not sure that fix works either, as it gives me:
```
  File "~/clusterfuzz/src/python/base/utils.py", line 949, in newstr_to_native_str
    return future_utils.native(str(s, encoding='utf-8')).encode()
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f937' in position 6: ordinal not in range(128)
```

**Comment by mbarbella-chromium** [comment]
Thanks for testing that. Thinking about it, it should be safe for us to skip inputs that have any sort of encoding errors here since it's guaranteed that they won't be of type newstr (which is why we need this hack until we finish migrating to Python 3). It still makes sense to keep the encoding='utf-8' bit, but I'll also handle the type errors and skip those keys if they occur.

**Comment by oliverchang** [comment]
> future_utils.native actually returns a unicode (since it's the native type backing newstr), so this should be safe.

Right, but then we call .encode() on the result, turning it into a "bytes" on Python3, which is not the "native" str.

**Comment by oliverchang** [comment]
@eepeep mentioned that this is still not working. @eepeep could you please share your PS1?

**Comment by mbarbella-chromium** [comment]
Ended up reverting the previous fix as well since it looks like that regressed the issue that block of code was trying to prevent.

**Comment by oliverchang** [comment]
OK, I can reproduce locally. I think the fix should be:

```python
def newstr_to_native_str(s):
  return future_utils.native(str(s, encoding='utf-8')).encode('utf-8')  
```

(Although as I previously mentioned, why do we need the encode() at all?)

**Comment by mbarbella-chromium** [comment]
If we didn't encode here each call site would need an encode after the fact since they're expecting strs. This function was implemented as a workaround for the cases where there were explicit str type checks. In cases where either a str or unicode could be accepted I suppose we wouldn't need the encode (I'm not sure how many if any of those there are), but unconditionally doing it here seemed cleaner.

Your point about bytes if a good one, but I think the entire function is problematic when moving to Python 3. When I initially wrote it I planned to delete it when doing the move instead of managing it for both versions, which won't actually be able to do. If we want it to be compatible with both, we should probably just detect the version and act as a no-op in Python 3. I think that can come later, when we actually start testing across both versions.
