### ISSUE TITLE
radamsa generates a lot of large testcases blowing up corpus

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1616]
I think @inferno-chromium was investigating a similar issue recently, but I'm afraid we may need to do a huge clean up now

While debugging https://github.com/google/oss-fuzz/issues/3449 I've noticed that 99% of large testcases are produced with radamsa:

```
$ ls -lS ghostscript_gstoraster_fuzzer/ | head -n 1000 | egrep radamsa | wc -l
990
```

**Comment by inferno-chromium** [comment]
This should fix it - https://github.com/google/clusterfuzz/pull/1581, waiting for some corpus pruning tasks to actually complete.

**Comment by inferno-chromium** [comment]
Ah i see a bug specific to OSS-Fuzz.
i think there is a bug in our untrusted corpus pruning task handling. Basically we dont propagate the last execution failure.

**Comment by oliverchang** [comment]
Let's strongly enforce this with a limit on our side. Since engines have a size limit anyway, it does not make sense to try running with larger inputs generated by external mutators etc.

**Comment by inferno-chromium** [comment]
gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer/ghostscript_gstoraster_fuzzer
it was not a file size issue here i think, but overall corpora was so big and kept growing since corpus pruning was exiting with exception and we never set last execution failed (OSS-Fuzz only).

but anyway, we should add some filter on upload_files in fuzz task, so that big files cannot sneak anytime.

**Comment by oliverchang** [comment]
+1 to a limit enforced before we upload.

**Comment by Dor1s** [comment]
1MB? or 5MB?

**Comment by inferno-chromium** [comment]
Since this is a global upload limit, i think higher than 1 mb makes sense [5/10/15mb ?]. Wdyt @Dor1s @oliverchang  ? I am really worried if seed corpuses have big files [e.g. media stuff] and we break those with this limit. this is reason i fixed everything else first rather than enforcing this limit.

Regarding this particular issue, it is currently getting fixed, corpus pruning task is clearing stuff currently, right now WIP, down from 19 gb to like 13 gb uptil now
gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer/ghostscript_gstoraster_fuzzer

**Comment by Dor1s** [comment]
i don't think anything greater 5MB is reasonable

**Comment by oliverchang** [comment]
+1 to 5MB. Anything larger probably won't be effective during fuzzing anyway.

**Comment by Dor1s** [comment]
Should we add the same logic to corpus pruning task? I don't think https://github.com/google/clusterfuzz/pull/1581 does it, i.e. any large files living in the cloud will stay there, as corpus pruning uploads them differently (via `rsync()`) from post-fuzzing merge

**Comment by inferno-chromium** [comment]
corpus pruning task shouldn't add new big testcases since it either works on its own corpus or corpus of other cross pollinated fuzzers (same limit). can add it later if need comes.

**Comment by Dor1s** [comment]
yes, new testcase uploading should be prevented by #1581, but what about files that are already in the corpus (#1581 will not delete them), or files that can be manually uploaded to the corpus?

**Comment by inferno-chromium** [comment]
I can only think of using -max_len in libfuzzer merge during corpus pruning task to mitigate this, but unsure if we should go aggressive there. If someone provides good seed corpus, that are sometimes large > 5 mb, say lets 6 mb, should we discard them.

**Comment by Dor1s** [comment]
I don't think there is much value in having good seed large files, if we cannot mutate them, as any mutated large file will be deleted now before uploading.

Using `-max_len` when merging with libFuzzer sounds brilliant to me! That way libFuzzer can get some use of large files and we won't have to iterate through all the sizes in python all the time

**Comment by inferno-chromium** [comment]
> I don't think there is much value in having good seed large files, if we cannot mutate them, as any mutated large file will be deleted now before uploading.
> 
> Using `-max_len` when merging with libFuzzer sounds brilliant to me! That way libFuzzer can get some use of large files and we won't have to iterate through all the sizes in python all the time

Feel free to do a fix if you get a chance (we have that constant in engine_common globals).

**Comment by Dor1s** [comment]
> Feel free to do a fix if you get a chance (we have that constant in engine_common globals).

Thanks again for the idea, done: https://github.com/google/clusterfuzz/pull/1734
