### ISSUE TITLE
What service account permissions are required for a bot run outside of GCP?

### ISSUE THREAD

**Issue by prestonvanloon** [google/clusterfuzz#1904]
I'm trying to add some bots outside of GCP. So far, I have determined that the service account needs access to some GCS buckets (which ones?) but I'm not sure what else it needs. With the service account having the GCS admin role, the bot appears to start but never shows up on the bots list and nothing seems to be logged.

```
...
All dependencies are now up-to-date!
Created bot directory /root/bot.
Running ClusterFuzz instance for linux bot.
```

Nothing else logged after 15 minutes and bot does not appear in `/bots`.

**Comment by inferno-chromium** [comment]
it needs cloud-platform scope, see https://github.com/google/clusterfuzz/blob/master/configs/test/gce/clusters.yaml#L97

**Comment by prestonvanloon** [comment]
I see, but does it really need access to everything? Is there a list of minimum required scopes for a bot?

**Comment by inferno-chromium** [comment]
When you check https://cloud.google.com/sdk/gcloud/reference/beta/compute/instances/set-scopes, it needs access to most things e.g.
bigquery for writing stats
datastore for storing db entities
logging for bot logging
pubsub for task queues
monitoring (optional)
compute-* can be skipped i think
storage-full or storage-rw atleast (for gcs)
servicecontrol probably yes
sql* can be skipped 
cloud-source-repos yes to download images from gcr
since you need almost everything, we went with cloud-platform, but you are on your own to figure out exact scopes.
