### ISSUE TITLE
Fuzzer Performance question

### ISSUE THREAD

**Issue by hpathuri** [google/clusterfuzz#1950]
a) Does Google upgrade to best performing AFL fuzzer if we use ClusterFuzz hosted solution?
b) Are the test case directory/corpus is in RAM or disk? Our understanding is that if CORPUS is on RAM based file system, performance is way faster.
c) How does pre-emption impacts fuzzer performance?

**Comment by inferno-chromium** [comment]
> a) Does Google upgrade to best performing AFL fuzzer if we use ClusterFuzz hosted solution?

You are free to choose the afl variant you want in your archives and it should just work. We are happy to accept patches to afl code as well. We are evaluating afl variants as well, see https://www.fuzzbench.com/reports/2020-07-13/index.html.

> b) Are the test case directory/corpus is in RAM or disk? Our understanding is that if CORPUS is on RAM based file system, performance is way faster.

This is upto you, you can put this in ram or disk, see https://github.com/google/clusterfuzz/blob/master/docker/base/setup_clusterfuzz.sh#L47
libFuzzer uses fuzzer-testcases-disk dir since corpus can get big, but you can create it anyway, like tmpfs or leave it as disk.

> c) How does pre-emption impacts fuzzer performance?

Results from those tasks are lost, but considering the cost gains, this is very minimal. Also, this is all configurable, instead of default
MAX_TESTCASES = 4
FUZZ_TEST_TIMEOUT = 4800
you can change these, so that each task is shorter and less results are lost. If you are thinking of some optimizations, we are happy to accept patches as well.
