### ISSUE TITLE
change bot numbers via webconsole

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#2045]
So just curious, we are trying to test out different combinations of bot numbers to find the optimal number of regular bots to pre-emptibles.  But it is a bit of a pain to constantly have to redeploy the whole app just to change the number of bots.  Is it possible to just modify the instance groups in the webconsole to adjust the number of bots?  Do the bots just self join the clusterfuzz once they are spun up?

**Comment by inferno-chromium** [comment]
Yes just change the number of bots in the instance group in google cloud console and everything will just work. it just creates more clusterfuzz bots which join the bot army. 

Just fyi, we have a cron that periodically checks for cluster of vms updates, but it does not trigger on manual updates that you do through google cloud console. reason being it needs an increment in version of template in clusters.yaml for any changes to happen. So, since clusters.yaml remains same, clusterfuzz does not override any of your cluster change updates. See https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/manage_vms.py#L234 for some understanding if you are interested.

**Comment by urbanenomad** [comment]
so the weird thing is that I would increment the instance group from 1 to 5 from the webconsole and it would spin up to 5 but after a few minutes it spins back down to 1 which is what the clusters.yaml file is set to.  Does the cronjob revert it back to the original setting in the clusters.yaml file?

**Comment by inferno-chromium** [comment]
> so the weird thing is that I would increment the instance group from 1 to 5 from the webconsole and it would spin up to 5 but after a few minutes it spins back down to 1 which is what the clusters.yaml file is set to. Does the cronjob revert it back to the original setting in the clusters.yaml file?

ah my bad, i forgot that bot count change are independent of template version. for this case, just deploy by adding a bailout , like "return" on this line - https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/manage_vms.py#L707 that way, auto-manage vm code will not come in your way of management till you are figuring out the right balance.

**Comment by amuthuirulappa** [comment]
The exact line that needs to be commented out appears to be 
```
def get(self):
    """Handle a get request."""
    if utils.is_oss_fuzz():
      manager_class = OssFuzzClustersManager
    else:
      manager_class = ClustersManager

    for project_id in _get_project_ids():
      manager = manager_class(project_id)
      #manager.update_clusters()
```
