### ISSUE TITLE
More info on MAX_TESTCASES and FUZZ_TEST_TIMEOUT

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2080]
Hello,

I was going through the options available for libfuzzer template. i have question regarding 
MAX_TESTCASES and FUZZ_TEST_TIMEOUT.

i saw the explanation of both in env.yaml file

MAX_TESTCASES = Maximum number of testcases to run in one cycle.
FUZZ_TEST_TIMEOUT = Maximum time the testcase are run in one fuzz cycle (0 - use default task lease timeout).

I wanted to know what exactly fuzzing cycle means and what is the relevance of the above options in the context of libfuzzer ?

**Comment by inferno-chromium** [comment]
in libfuzzer/afl/honggfuzz context, MAX_TESTCASES is actually one fuzzing session without crashes. Usually we try to run 4 testcases of 1-1.5 hr each (FUZZ_TEST_TIMEOUT). but this is customizable. only thing to remember is preemptible bots, they can die anytime in 24 hour interval, so keeping this low helps to save results [since sessions are not resumable].
