### ISSUE TITLE
VM distribution to jobs is not uniform.

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2082]
Hi Team,

I have setup clusterfuzz on Gcloud. i have 100 preemptible machines which are running around 33 jobs. All the jobs are ASAN based. 

Ideally it should be allocating 3 VMs per job but i dont see that happening. some VMs are allocated 3 and some are allocated 1.

I am trying to understand this behaviour and possible reasons of it. 

Also can we get data of what preemptible VM ran which job and for how much time before dying. This would help me to understand more about bots behaviour.

**Comment by inferno-chromium** [comment]
It adjusts fuzzer and job weights based on following conditions:
https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/fuzzer_and_job_weights.py#L107

If a fuzzer is crashing often, has timeout or oom or slow units or coverage does not change, then it auto-adjusts to lower weights. Check if those jobs have fuzzers that are crashing often. Also, this is a randomized distribution, so maybe best to monitor over a day and capture data rather than looking at a particular point. Like check /fuzzer-stats page for daily stats.
