### ISSUE TITLE
ubuntu 18.04 support

### ISSUE THREAD

**Issue by ravi50041** [google/clusterfuzz#2274]
Hello,

Some of my modules need ubuntu 18 to do fuzzing. below dockerfile mentioned ubuntu 16. 

https://github.com/google/clusterfuzz/blob/master/docker/base/Dockerfile

can we change it to ubuntu 18 and use it as the base?

**Comment by inferno-chromium** [comment]
Yes you can build images using ubuntu18, for us we are stuck due to msan requirements.

**Comment by urbanenomad** [comment]
So we did upgrade our non-prod cluster to ubuntu18 and we had to modify a few things for it to build properly.  We are using NFS in GCP with Google Filestore in both our prod and non-prod or set the LOCAL_GCS_BUCKETS_PATH to where we mounted the NFS folder and we started to see a bunch of these errors.  

Source file /opt/gcs/blobs.clusterfuzzsbx8.appspot.com/objects/36267b00-14bb-473d-b65b-1521895d34ce for copy not found

"/opt/gcs" is the container path to the NFS storage.  When we look in the NFS folder we see that that file was not created.  We were wondering what is the process of writing to the "blobs" file store and whether it is different in GCS vs local storage?  

Since our prod cluster is using ubuntu 16 and using the NFS as file store and the exact same job works fine there.  So we believe it has to do with our non-prod environment running both ubuntu 18 and using NFS.  And we know it has to do with NFS and ubuntu 18 because when we revert our non-prod back to using GCS with ubuntu 18 it works fine there.  Any help would be much appreciated.  I know ubuntu 18 in the bot container is not yet supported but it looks like something is failing when we use the local file store.

On a side note we have found for very large clusters we see about a 40% discount in overall cost when we switched to using NFS.  Our prod cluster which has about 105 bots went from $3500/month to about $2200/month

**Comment by inferno-chromium** [comment]
you can read the code here and suggest fixes if needed, i think difference is we expect these paths to exist, so can suggest pr to create those paths if dont exist - https://github.com/google/clusterfuzz/blob/master/src/python/google_cloud_utils/storage.py#L327
and then add tests in https://github.com/google/clusterfuzz/blob/master/src/python/tests/core/google_cloud_utils/storage_test.py
