### ISSUE TITLE
Propagate bot init errors to console

### ISSUE THREAD

**Issue by mykter** [google/clusterfuzz#253]
I broke my linux-init.yaml file and the only observable result that I could find in the console was nothing was happening. I worked out what was going on when I ssh'ed in and tried `systemctl start clusterfuzz` - it failed. Presumably some other part of the system is calling the runcmd - it would be helpful if whatever it is passed the failure up the stack so it was visible in the errors console.

The full error was only visible with `systemctl status clusterfuzz.service` - but a hint that this was where the problem was would have been very useful.

**Comment by inferno-chromium** [comment]
linux-init.yaml is the startup script. If anything fails before ClusterFuzz system starts, there is no easy way for system to send that info back to the Appengine Error Reporting / Stackdriver (since ClusterFuzz runtime talks to those and if ClusterFuzz itself didn't start, then we can't do much about it). 

We recommend that you can run "journalctl -f" after sshing into the bot to see what went wrong.

To check if a bot is running successfully, it is best to start from "/bots" page and see if the bot shows up there. If not, then start with searching the stackdriver logs and search by that bot name string. That will tell if the bot successfully started. If that failed, then make sure that the bot is successfully created/recreated by going to Google Cloud console->Compute Engine->bots list to verify that bot is created/running. If you see the bot, then the only way a failure happens is if you make changes to startup script like you did with linux-init.yaml. Do the journalctl to verify that ClusterFuzz service runs.

Is everything working fine for you now ? We welcome documentation improvements PRs (concise please) that help to improve experience for everyone.

**Comment by inferno-chromium** [comment]
documention change now tracked in https://github.com/google/clusterfuzz/issues/252. Also, you said in #252 that things work for you now, so closing this.
