### ISSUE TITLE
Re-enable fork mode strategy for libFuzzer on Windows

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#267]
This is currently blocked on windows command line size limitation. @jonathanmetzman says to explore it enabling it with subset strategy (since it will result in fewer corpus items to be used). we need to also look into fixing this properly in LLVM itself with not passing corpus paths via command line and instead using like files or something.

@kcc for ideas, otherwise we will look into this sometime in Q2. For Windows, fork mode is even more important due to lack of AFL there.

**Comment by jonathanmetzman** [comment]
I have a better, more comprehensive solution. 
Using `CreateProcess` instead of `system` gives us up to [32,768 chars](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters) chars for arguments instead of [8192](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation). The two problems with this solution are:
1. Are 32,768 chars enough?
2. `CreateProcess` doesn't support everything that system does, it doesn't execute a `cmd.exe` command, so things like redirecting stdout and stderr will have to be handled differently.

Some more ideas for working around this limitation (some of which are a bit frightening) are [here](https://devblogs.microsoft.com/oldnewthing/?p=41543).

**Comment by jonathanmetzman** [comment]
Reid thinks the best solution may be to pass a file containing corpus elements to use, instead of directly passing the corpus elements via command line

**Comment by jonathanmetzman** [comment]
I have a solution that implements the file technique [here](https://reviews.llvm.org/D60980)
I should be ready to land it soon.

**Comment by jonathanmetzman** [comment]
Landed it.
