### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by boni-sha** [google/clusterfuzz#2806]
Given that google is getting rid of out of band oauth backend flow soon i don't see a new release tag with the given changes. Are there any plans to release one soon?

**Comment by oliverchang** [comment]
Hi,

The only real impact should have been addressed back in https://github.com/google/clusterfuzz/issues/2576, and the latest release (v2.5.7) does include this. There's some dead/stale code in this repo that references oob, but I'll remove these shortly. 

That said, it has been a while since we cut a release -- we'll do it soon.
