### ISSUE TITLE
Centipede integration tests spuriously failing

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3622]
This is breaking CI (and blocking our normal deploy). Please fix this.
Example: https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/56eb4dfb-f435-4fdc-afa3-549a26405d05?project=clusterfuzz-testing-public&e=-13802955&mods=logs_tg_prod

**Comment by Alan32Liu** [comment]
Thanks! I will check this.

**Comment by Alan32Liu** [comment]
Hmm, not sure what exactly happened, but this seems benign.
Corpus minimization reduced 7 testcases to 4, instead of 3 (excluding the crash).
The minimized test cases look fine to me: They are not the same, some are removed, and the crasher is preserved correctly.
Recording the test case files before and after minimization below, in case I missed something, or this happens again in the future.

```
# Before minimization:

filename: 2
filecontent: sdfsdfdsfsda

filename: 5
filecontent: fasdfsdfasdfkl:jkl:j

filename: 3
filecontent: asdfsdsadjkl:kl:

filename: unmin_crash
filecontent: ?f???u???z?
filename: 4
filecontent: werwerwerwq

filename: 1
filecontent: asfsdfsdaf

filename: 6
filecontent: asfsdasadf:
```

```
# After minimization:

filename: 85c90964b01b823c6c992e317eb623be0f96dff0
filecontent: sdfsdfdsfsda

filename: 756fd7e16860553b4c5ebda85cfd69e25fe972bd
filecontent: fasdfsdfasdfkl:jkl:j

filename: 877f1685d9aa9c4bed02d3a7a6541bc1147818a7
filecontent: asfsdasadf:

filename: e451f1787f0b82631be9cb587d10791efff88c4d
filecontent: asdfsdsadjkl:kl:

# Crash is preserved in `crash_corpus`.
```
