### ISSUE TITLE
Severity analyzer gives wrong severity for Chromium bug

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#363]
https://bugs.chromium.org/p/chromium/issues/detail?id=945370

**Comment by inferno-chromium** [comment]
Might be a quick bug to fix, @oliverchang can take a look.

**Comment by jonathanmetzman** [comment]
I think I already fixed this: https://github.com/google/clusterfuzz/pull/280

**Comment by inferno-chromium** [comment]
@jonathanmetzman - i dont see BrowserProcessSubThread in that stacktrace for testcase in c#14.

**Comment by jonathanmetzman** [comment]
Ah I must have talking about crbug.com/942898

**Comment by oliverchang** [comment]
Bug doesn't appear to be in the process detection code, since plugging in the stacktrace to it gives the correct result. Will dig into this a bit more later..

**Comment by oliverchang** [comment]
Ok, I think this is because the stacktrace itself is flaky, at least with the bottom most frames. In some runs, it gives a BrowserMain frame, in other runs, it looks like this:

```
    #9 0x55d2dd3eb91b in content::StartBrowserTaskScheduler() content/browser/startup_helper.cc:95:39
    #10 0x55d2e372d5d1 in content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) content/app/content_main_runner_impl.cc:924:7
    #11 0x55d2e372cedb in content::ContentMainRunnerImpl::Run(bool) content/app/content_main_runner_impl.cc:878:12
    #12 0x55d2e38941c6 in service_manager::Main(service_manager::MainParams const&) services/service_manager/embedder/main.cc:415:29
    #13 0x55d2e3726d3c in content::ContentMain(content::ContentMainParams const&) content/app/content_main.cc:19:10
    #14 0x55d2d9a89c2e in ChromeMain chrome/app/chrome_main.cc:103:12
    #15 0x7fccc4e6f2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
```

Which has neither BrowserMain nor BrowserProcessSubThread. 

In this case, the CF testcase still has BrowserMain in it with the wrong severity, because symbolize_task finished last, and it happened to get a stack with BrowserMain but it doesn't recalculate the severity.

**Comment by oliverchang** [comment]
should be fixed now.
