### ISSUE TITLE
Py2to3: Replace App Engine module with firebase auth

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#399]
As part of Python 3 migration (#183)

**Comment by oliverchang** [comment]
@inferno-chromium just a FYI that I've started on this, so that we don't duplicate work :)

**Comment by inferno-chromium** [comment]
This will be awesome, thanks @oliverchang for working on this. I think this will also help to get rid of remaining testbed instances (other than these below, there is memcache but that is already in plans to change to something else).

```
src/python/tests/appengine/handlers/base_handler_test.py:from google.appengine.ext import testbed
src/python/tests/appengine/handlers/base_handler_test.py:    self.testbed = testbed.Testbed()
src/python/tests/appengine/handlers/base_handler_test.py:    self.testbed.activate()
src/python/tests/appengine/handlers/base_handler_test.py:    self.testbed.init_user_stub()
src/python/tests/appengine/handlers/base_handler_test.py:    self.testbed.deactivate()
src/python/tests/appengine/handlers/fuzzer_stats_data/testFuzzer_1_fuzzer_None_by-job_2016-10-20_2016-10-21.txt:    "projectId": "testbed-test",
src/python/tests/appengine/handlers/fuzzer_stats_data/testFuzzer_None_by-fuzzer_2016-10-20_2016-10-22.txt:    "projectId": "testbed-test", 
src/python/tests/appengine/handlers/fuzzer_stats_data/testFuzzer_job_by-fuzzer_2016-10-20_2016-10-21.txt:    "projectId": "testbed-test", 
src/python/tests/appengine/handlers/issue_redirector_test.py:from google.appengine.ext import testbed
src/python/tests/appengine/handlers/issue_redirector_test.py:    self.testbed = testbed.Testbed()
src/python/tests/appengine/handlers/issue_redirector_test.py:    self.testbed.activate()
src/python/tests/appengine/handlers/issue_redirector_test.py:    self.testbed.init_user_stub()
src/python/tests/appengine/handlers/issue_redirector_test.py:    self.testbed.deactivate()
src/python/tests/appengine/libs/handler_test.py:from google.appengine.ext import testbed
src/python/tests/appengine/libs/handler_test.py:    self.testbed = testbed.Testbed()
src/python/tests/appengine/libs/handler_test.py:    self.testbed.activate()
src/python/tests/appengine/libs/handler_test.py:    self.testbed.init_user_stub()
src/python/tests/appengine/libs/handler_test.py:    self.testbed.deactivate()
```

**Comment by inferno-chromium** [comment]
some issues remaining, some are lower priority than others, can test with project clusterfuzz-aarya-test or your own:

1. firebase api key is in bucket_replacements array, so gcloud bucket creation in create_config fails due to trying to create it as bucket.
2. After deployment, i see this error -  
"This domain (clusterfuzz-aarya-test.appspot.com) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab."
Can this be automated or we need to document this step in doc.
3. it is not clear when to get api key in documentation, need to mention project settings -> web api key.
4. lower priority: sign in screen says "continue to sign to cluster-fuzz.firebaseapp.com", this can be changed to our domain, but need more config change.

**Comment by oliverchang** [comment]
@inferno-chromium re 2. do you have any good ideas for how to do this? I see some instructions at, but I'm not sure that it is possible with our top level domains (i.e. clusterfuzz.com/oss-fuzz.com), because they're used by App Engine already. We could probably add a login.clusterfuzz.com domain to Firebase to make this work though.

**Comment by inferno-chromium** [comment]
Only saw https://stackoverflow.com/questions/46135993/how-to-change-the-app-name-for-firebase-authentication-what-the-user-sees but didnt get a chance to try. it is lower priority, so thanks a ton for all the other nice fixes.

**Comment by inferno-chromium** [comment]
<anything>.clusterfuzz.com and <anything>.oss-fuzz.com should be perfect, like you mentioned.

**Comment by oliverchang** [comment]
This is all done now.
