### ISSUE TITLE
knowing clusterfuzz

### ISSUE THREAD

**Issue by nikul** [google/clusterfuzz#589]
What does clusterfuzz exactly?
Can I use it in php projects to find bugs, hacking issue etc.?
If yes how can I achieve it? how does it scan any website projects files?

**Comment by Dor1s** [comment]
Hi @nikul,

> What does clusterfuzz exactly?

ClusterFuzz is a fuzzing infrastructure than manages virtual and physical machines (so called "bots") in order to perform fuzzing at scale.\

> Can I use it in php projects to find bugs, hacking issue etc.?

Sure, you just need to write a good fuzzer for your target application and then run in on a ClusterFuzz instance.

> If yes how can I achieve it?

Please check out our documentation: https://google.github.io/clusterfuzz/

> how does it scan any website projects files?

I don't think ClusterFuzz does that.
